baseURL = "https://vishvAsa.github.io/kalpAntaram/"
languageCode = "en-us"
title = "कल्पान्तरे विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vishvAsa/kalpAntaram/edit/content/"
  contactLink = "https://github.com/vishvAsa/kalpAntaram/issues/new"
  build_img = "https://github.com/vishvAsa/kalpAntaram/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/vishvAsa/kalpAntaram/actions/workflows/build.yml"
  env = "production"  
  # disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2


[module]

  [[module.mounts]]
    source = "../kalpAntaram-content"
    target = "content"

  [[module.mounts]]
    source = "../kalpAntaram-static"
    target = "static"

